name: pokedex
description: Pokedex
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^4.0.6
  get_it: ^7.2.0
  flutter_svg: ^1.1.6
  go_router: ^6.0.1
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  formz: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - 'assets/'
